title: rasjani @ github.io
email: jani.mikkonen@gmail.com
author: Jani Mikkonen
description: code - do we need something else?
url: https://rasjani.github.io
linkedin_username: mikkonenjani
github_username:  rasjani
twitter_username:  _rasjani_
mastodon_username: "@rasjani@hachyderm.io"
mastodon_url: https://hachyderm.io/@rasjani
stackoverflow_id: 108538
google_analytics: UA-155380149-1
paginate: 5
paginate_path: "/blog/page:num/"
name: rasjani @ github.io
description: code - do we need something else?
url: https://rasjani.github.io
feed:
  path: feed.xml
  posts_limit: 10000
  tags: true
plugins:
  - jekyll-mentions
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-feed
markdown: kramdown
highlighter: rouge
repository: rasjani/rasjani.github.io
collections:
  projects:
    output: true
    permalink: /projects/:path/
